version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: cimg/ruby:3.3.0
    environment:
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: land
      RAILS_ENV: test
      COVERAGE: true
      TZ: /usr/share/zoneinfo/America/Chicago
  postgres: &postgres
    image: cimg/postgres:13.4
    environment:
      POSTGRES_DB: land_test
      POSTGRES_USER: land

jobs:
  build:
    working_directory: ~/land/land_index
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - land-
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - save_cache:
          key: land-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/land/land_index/vendor/bundle

  test:
    working_directory: ~/land/land_index
    parallelism: 1
    docker:
      - *default_docker_ruby_executor
      - *postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - land-
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - run: sudo apt -y update; sudo apt install -y postgresql-client
      - run:
          name: Install postgresql-client
          command: sudo apt install -y postgresql-client || true
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: |
            bundle exec rails db:setup --trace
      - run:
          name: Run RSpec (headless)
          command: |
            mkdir /tmp/test-results
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - codecov/upload
      - store_artifacts:
          path: coverage

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
